# Starter pipeline

trigger:
  paths:
    include:
    - '/configfiles/testFile.*'


stages:
- stage: GetService 

  jobs:
    - job: 'GetService'
    
      pool:
        name: ThingWorx
    
      steps:
      - task: PowerShellOnTargetMachines@3
        inputs:
          Machines: 'hkgs7336.corp.knorr-bremse.com'
          InlineScript: 'Write-Output "Hello World"'

      