# Starter pipeline

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    - checkout: self
      persistCredentials: true
    ant -noinput -buildfile build-extension.xml
    echo $(Agent.BuildDirectory)
    echo $(Agent.HomeDirectory)
    echo $(Build.ArtifactStagingDirectory)
    echo $(Build.BinariesDirectory)
    echo $(Build.Repository.LocalPath)
    echo $(Build.SourcesDirectory)
    echo $(System.DefaultWorkingDirectory)
    git add $(Build.SourcesDirectory)\build\distributions\KBGlobalsmartKPI.zip
    git push https://nitin-sriv:Neutral@06@github.com/DevOpsOrgPlayground1/KBGlobalSmartKPI
  displayName: 'Creating a TWX Extension and checkin'
