# Starter pipeline

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- checkout: self
  persistCredentials: true

- script: |
    git config --global user.email $(Build.RequestedForEmail) 
    git config --global user.name "nitin-sriv"
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: |
    git checkout -b main
    ant -noinput -buildfile build-extension.xml
    git add -A
    echo "added extension zip"
    git status
    git commit -m "deployment $(Build.BuildNumber)"
    echo "commited extension zip"
    git branch -vv
    echo "list tracking branches"
    git ls-remote
    echo "list remote branches"
    git push --set-upstream origin main
  displayName: 'Creating a TWX Extension and checkin'
