# Starter pipeline

trigger:
  paths:
    include:
    - '/configfiles/testFile.*'


stages:
- stage: GetService 

  jobs:
    - job: 'GetService'
    
      pool:
        vmImage: windows-latest
    
      steps:
      - task: PowerShellOnTargetMachines@3
        inputs:
          Machines: 'hkgs7336'
          InlineScript: 'Get-Service -computername hkgs7336'