# Starter pipeline

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- checkout: self
  persistCredentials: true

- script: |
    git config --global user.email nitin.srivastava@knorr-bremse.com 
    git config --global user.name "nitin-sriv"
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: |
    git checkout -b temp
    git status
    git checkout master
    git status
    ant -noinput -buildfile build-extension.xml
    git add $(Build.SourcesDirectory)\build\distributions\KBGlobalsmartKPI.zip
    git commit -m "deployment $(Build.BuildNumber)"
    git status
    git push --set-upstream origin temp
    git status

  displayName: 'Creating a TWX Extension and checkin'
