# Starter pipeline

trigger:
  paths:
    include:
    - '/configfiles/testFile.*'


stages:
- stage: GetService 

  jobs:
    - job: 'GetService'
    
      pool:
        vmImage: windows-latest
    
      steps:
      - task: PowerShellOnTargetMachines@3
        inputs:
          Machines: '100.249.84.36'
          UserName: 'adm-srivastn'
          UserPassword: 'Knorr456%'
          InlineScript: |
            # Write your powershell commands here.
            
            Write-Output "Hello World"