# Starter pipeline

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- checkout: none
  persistCredentials: true

- script: |
    git config --global user.email nitin.srivastava@knorr-bremse.com 
    git config --global user.name "nitin-sriv"
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: |
    git rm --cached KBGlobalSmartKPI
    git init
    git clone https://github.com/DevOpsOrgPlayground1/KBGlobalSmartKPI
    git checkout 
    ant -noinput -buildfile build-extension.xml
    git add -A
    echo "added extension zip"
    git status
    git commit -m "deployment $(Build.BuildNumber)"
    echo "commited extension zip"
    git branch -vv
    echo "list tracking branches"
    git ls-remote
    echo "list remote branches"
    git push 
  displayName: 'Creating a TWX Extension and checkin'
