# Starter pipeline

trigger:
- none

pool:
  vmImage: windows-latest
    
steps:
- checkout: self
  persistCredentials: true

- script: |
    git config --global user.email nitin.srivastava@knorr-bremse.com 
    git config --global user.name "nitin-sriv"
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: |
    git checkout -b main
    ant -noinput -buildfile build-extension.xml
    git add -A
    echo "added extension zip"
    git status
    git commit -m "deployment $(Build.BuildNumber)"
    echo "commited extension zip"
    git branch -vv
    echo "list tracking branches"
    git ls-remote
    echo "list remote branches"
    git push --set-upstream origin main
  displayName: 'Creating a TWX Extension and checkin'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'build/distributions'
    Contents: 'KBGlobalsmartKPI.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: BuildOutputs

- task: CmdLine@2
  inputs:
      script: |
        curl -X POST -F "file=build/distributions/KBGlobalsmartKPI.zip" -H "appKey:f456601d-c8b2-4a80-8497-f6ca91fd69bd" -H "Accept:application/json" -H "X-XSRF-TOKEN:TWX-XSRF-TOKEN-VALUE" -H "Content-Type:multipart/form-data" https://hkgs7336.corp.knorr-bremse.com/Thingworx/ExtensionPackageUploader