# Starter pipeline

trigger:
  paths:
    include:
    - '/configfiles/testFile.*'


stages:
- stage: GetService 

  jobs:
    - job: 'GetService'
    
      pool:
        name: ThingWorx
    
      steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host "Hello World"