# Starter pipeline

trigger:
  paths:
    include:
    - '/configfiles/testFile.*'


stages:
- stage: Get Service 

  jobs:
    - job: 'GetService'
      pool:
        name: ThingWorx
    
      steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'Get-Service -computername hkgs7336.corp.knorr-bremse.com'